config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/landing', to: 'landing#index'
  post '/daily_feelings', to: "daily_feeling#create"
  get '/survey', to: 'survey#index'
  get '/boost', to: 'boost#show'
  post '/journal_entries', to: 'journal_entries#create'
  get '/journal', to: 'journal_entries#index'

  get '/profile', to: 'users#show'
  post '/survey', to: 'survey#create'

  resources :buddies, except: :show
  resources :users, only: [:edit, :update, :destroy]

  get '/preferences', to: 'users/preferences#index'
  get '/preferences/edit', to: 'users/preferences#edit'
  patch '/preferences', to: 'users/preferences#update'

  get '/dbt', to: 'dbt#show'
  post '/feedback', to: 'feedback#create'

  delete '/logout', to: 'sessions#destroy'
  get '/auth/google_oauth2', as: 'google_login'
  get '/auth/google_oauth2/callback', to: 'users#create'

  get '/auth/spotify', as: 'spotify'
  get '/auth/spotify/callback', to: 'spotify#create'
end

app/models/activity_preference.rb
class ActivityPreference < ApplicationRecord
  belongs_to :user
  validates_presence_of :description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user
  validates_presence_of :first_name, :last_name, :email, :phone_number
  validates :phone_number, numericality: true, length: { minimum: 10, maximum: 10 }
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/daily_feeling.rb
class DailyFeeling < ApplicationRecord
  belongs_to :user
  validates_presence_of :feeling
end

app/models/dbt.rb
class Dbt < ApplicationRecord
  validates_presence_of :quote
end

app/models/dbt_quote.rb
class DbtQuote < ApplicationRecord
  validates_presence_of :quote
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  validates_presence_of :activity, :helpful, :again, :shift
end

app/models/feeling_category.rb
class FeelingCategory < ApplicationRecord
  belongs_to :feeling_preference
  belongs_to :user
  validates_presence_of :category
end

app/models/feeling_preference.rb
class FeelingPreference < ApplicationRecord
  belongs_to :user
  validates_presence_of :feeling
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user
  validates_presence_of :entry
end

app/models/media_preference.rb
class MediaPreference < ApplicationRecord
  belongs_to :user
end

app/models/music_preference.rb
class MusicPreference < ApplicationRecord
  belongs_to :user
  validates_presence_of :genre
end

app/models/resource_preference.rb
class ResourcePreference < ApplicationRecord
  belongs_to :user
end

app/models/time_preference.rb
class TimePreference < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :first_name, :last_name, :email, :google_token
  validates_uniqueness_of :email
  has_many :buddies, dependent: :destroy
  has_many :feeling_preferences, dependent: :destroy
  has_many :daily_feelings, dependent: :destroy
  has_many :activity_preferences, dependent: :destroy
  has_many :feeling_categories, dependent: :destroy
  has_many :music_preferences, dependent: :destroy
  has_many :journal_entries, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_one :resource_preference, dependent: :destroy
  has_one :media_preference, dependent: :destroy
  has_one :time_preference, dependent: :destroy
end

app/controllers/boost_controller.rb
class BoostController < ApplicationController
  before_action :logged_in?, :survey_not_completed?

  def show
    if params["completed"]
      @completed = true
    else
      if params['journal']
        @journal_complete = true
      end
      if current_user.spotify_token == nil && current_user.resource_preference[:music] == true
        flash[:error] = 'Please sign-in to a spotify premium account to get a song suggestion'
        redirect_to '/landing'
      else
        facade = ResourceFacade.new(current_user)
        facade.get_resource
        session[:suggestion] = facade.suggestion
          if session[:suggestion] == 'buddy' && current_user.buddies.empty?
            flash[:error] = 'Pleaese add a buddy to get a buddy suggestion'
            redirect_to '/buddies/new'
          else
            render locals: { resource_facade: facade }
        end
      end 
    end
  end
end

app/controllers/dbt_controller.rb
class DbtController < ApplicationController
  before_action :logged_in?, :survey_not_completed?
  def show
    @entry = current_user.journal_entries.new
    @quote = DbtQuote.all.sample
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
    BuddyMailer.inform(current_user, params[:email]).deliver_now
    flash[:notice] = "Email sent to notify your buddy!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, :survey_not_completed?, except: :create

  def create
    user = User.find_by(email: email)
    user ? found_user_redirect(user) : setup_new_user
  end

  def show; end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    if @user.save
      flash[:success] = 'Profile Updated!'
      redirect_to '/profile'
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    current_user.destroy
    session.clear
    flash[:notice] = 'Account deleted.'
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end

    def found_user_redirect(user)
      session[:user_id] = user.id
      redirect_to landing_path
      flash[:success] = 'Login Successful'
    end

    def setup_new_user
      user = make_user
      user.save ? new_user_redirect(user) : failed_user_redirect
    end

    def make_user
      User.new(
        first_name: first_name,
        last_name: last_name,
        email: email,
        google_token: token
      )
    end

    def new_user_redirect(user)
      session[:user_id] = user.id
      flash[:success] = 'Login Successful'
      redirect_to survey_path
    end

    def failed_user_redirect
      flash[:error] = 'Failed to Login'
      redirect_to '/'
    end

    def first_name
      f_name = request.env['omniauth.auth']['info']
      f_name ? f_name['first_name'] : nil
    end

    def last_name
      l_name = request.env['omniauth.auth']['info']
      l_name ? l_name['last_name'] : nil
    end

    def email
      email = request.env['omniauth.auth']['info']
      email ? email['email'] : nil
    end

    def token
      token = request.env['omniauth.auth']['credentials']
      token ? token['token'] : nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/partials/_activity.html.erb
<section id='activity'>
  <p>Your recommended activity: <%= resource_facade.resource.description %></p>
</section>

app/views/partials/_buddy_crud.html.erb
<center>
  <%= form_tag path, method: method do %>
    <%= label_tag :first_name %>
    <%= text_field_tag :first_name, buddy ? buddy.first_name : nil %>
    <%= label_tag :last_name %>
    <%= text_field_tag :last_name, buddy ? buddy.last_name : nil %>
    <%= label_tag :email %>
    <%= text_field_tag :email, buddy ? buddy.email : nil %>
    <%= label_tag :phone_number %>
    <%= text_field_tag :phone_number, buddy ? buddy.phone_number : nil %>
    <%= submit_tag button %>
  <% end %>
</center>

app/views/partials/_buds.html.erb
<section id='buddy'>
  <p id='name'>Send a text to or call <%= resource_facade.resource.first_name + ' ' + resource_facade.resource.last_name %>
  <p id='number'>at <%= number_to_phone(resource_facade.resource.phone_number) %></p>
</section>

app/views/partials/_feedback.html.erb
<center>
  <h2>Feedback about your activity</h2>

  <%= form_tag '/feedback', method: :post do %>
    <h3>Did you find the recommendation helpful?</h3>
    <%= label_tag "Yes" %>
    <%= radio_button("helpful", "y/n", true) %>
    <%= label_tag "No"%>
    <%= radio_button("helpful", "y/n", false) %>

    <h3>Would you benefit from doing it again?</h3>
    <%= label_tag "Yes" %>
    <%= radio_button( "again", "y/n", true) %>
    <%= label_tag "No"%>
    <%= radio_button( "again", "y/n", false) %>

    <h3>Did this help your mood shift?</h3>
    <%= label_tag "Yes" %>
    <%= radio_button( "shift", "y/n", true) %>
    <%= label_tag "No"%>
    <%= radio_button( "shift", "y/n", false) %>

    <p><%= submit_tag 'Submit' %></p>
  <% end %>
</center>

app/views/partials/_journal.html.erb
<p>Journal about whatever comes up for you, then click save.</p>
<section id='journal-entry'>

  <%= form_for resource_facade.new_entry, url: '/journal_entries?resource=true' do |f| %>
    <p>
      <%= f.text_area(:entry, size: '100x20') %>
    </p>
    <p>
      <%= f.submit 'Save', method: :post %>
    </p>
  <% end %>
</section>

app/views/partials/_media.html.erb
<section id='media'>
  <p>Penpal selected the following image to lift your spirits:</p>
  <%= image_tag(resource_facade.resource.image_url,size: "300x300") %>
</section>

app/views/partials/_music.html.erb
<section id='music'>
  <p>Penpal selected the following song to lift your spirits:</p>
  <%= image_tag(resource_facade.resource.image,size: "300x300") %>
  <p>Song by:   <%= resource_facade.resource.artist_name %>   </p>
  <p><%= link_to resource_facade.resource.song_name, resource_facade.resource.url %></p>
</section>

app/views/partials/_nav.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>


<nav class="navbar navbar-inverse">
  <div class="container-fluid left">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">P</button>
    </div>
    <div class="collapse navbar-collapse right" id="myNavbar">
      <ul class="nav navbar-nav nav-colec">
        <li class="active"><%= link_to 'Home', landing_path %></li>
        <li><%= link_to 'Profile', profile_path, method: :get %></li>
        <li><%= link_to 'Journals', journal_path, method: :get %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_preferences.html.erb
<center>
  <%= form_tag path, method: method do %>
    <h5>I often feel: </h5>
    <%= label_tag "feelings[sad]", "Sad" %>
    <%= check_box_tag "feelings[sad]", "sad" %>
    <%= label_tag "feelings[down]", "Down" %>
    <%= check_box_tag "feelings[down]", "down" %>
    <%= label_tag "feelings[alone]", "Alone" %>
    <%= check_box_tag "feelings[alone]", "alone" %>
    <%= label_tag "feelings[unmotivated]", "Unmotivated" %>
    <%= check_box_tag "feelings[unmotivated]", "unmotivated" %>
    <%= label_tag "feelings[mad]", "Mad" %>
    <%= check_box_tag "feelings[mad]", "mad" %>

    <h5>I notice that I feel this way more often: </h5>
    <%= label_tag "time[morning]", "In the morning" %>
    <%= check_box_tag "time[morning]", "morning" %>
    <%= label_tag "time[mid-day]", "Mid-day" %>
    <%= check_box_tag "time[mid-day]", "midday" %>
    <%= label_tag "time[before-bed]", "Before bed" %>
    <%= check_box_tag "time[before-bed]", "before_bed" %>
    <%= label_tag "time[random]", "Random times" %>
    <%= check_box_tag "time[random]", "random" %>

    <h5>When I feel this way, it can be helpful to: </h5>
    <%= label_tag "resources[music]", "Listen to my favorite music" %>
    <%= check_box_tag "resources[music]", "music" %>
    <%= label_tag "resources[activity]", "Perform an activity I enjoy" %>
    <%= check_box_tag "resources[activity]", "activity" %>
    <%= label_tag "resources[buddy]", "Talk to a friend or family member" %>
    <%= check_box_tag "resources[buddy]", "buddy" %>
    <%= label_tag "resources[media]", "View cute animal pictures" %>
    <%= check_box_tag "resources[media]", "media" %>
    <%= label_tag "resources[journal]", "Journal" %>
    <%= check_box_tag "resources[journal]", "journal" %>

    <h5>My favorite music genre is: </h5>
    <%= label_tag "music[rock]", "Rock" %>
    <%= check_box_tag "music[rock]", "rock" %>
    <%= label_tag "music[r&b-soul]", "R&B/Soul" %>
    <%= check_box_tag "music[r&b-soul]", "rnbsoul" %>
    <%= label_tag "music[folk/indie]", "Folk/Indie" %>
    <%= check_box_tag "music[folk/indie]", "folkindie" %>
    <%= label_tag "music[custom]", "Other" %>
    <%= text_field_tag "music[custom]" %>
    <%= text_field_tag "music[custom_2]" %>

    <h5>I love looking at these types of images: </h5>
    <%= label_tag "media[dogs]", "Dogs" %>
    <%= check_box_tag "media[dogs]", "dogs" %>
    <%= label_tag "media[cats]", "Cats" %>
    <%= check_box_tag "media[cats]", "cats" %>
    <%= label_tag "media[animals]", "All animals" %>
    <%= check_box_tag "media[animals]", "animals" %>
    <%= label_tag "media[babies]", "Baby humans" %>
    <%= check_box_tag "media[babies]", "babies" %>
    <%= label_tag "media[landscapes]", "Landscapes" %>
    <%= check_box_tag "media[landscapes]", "landscapes" %>
    <%= label_tag "media[celestial]", "Celestial" %>
    <%= check_box_tag "media[celestial]", "celestial" %>

    <h5>Please fill in the following with activities that you enjoy doing: </h5>
    <%= label_tag "activities" %>
    <%= text_area_tag "activity[activity_1]" %>
    <%= text_area_tag "activity[activity_2]" %>
    <%= text_area_tag "activity[activity_3]" %>

    <%= submit_tag button %>
  <% end %>
</center>

app/views/partials/_spotify.html.erb
<html>
  <body>

    <script src="https://sdk.scdn.co/spotify-player.js"></script>
    <script>
      window.onSpotifyWebPlaybackSDKReady = () => {
        const token = <%= current_user.spotify_token %>;
        const player = new Spotify.Player({
          name: 'Web Playback SDK Quick Start Player',
          getOAuthToken: cb => { cb(<%= current_user.spotify_token %>); }
        });

        // Error handling
        player.addListener('initialization_error', ({ 'Initialization Error' }) => { console.error(message); });
        player.addListener('authentication_error', ({ 'Authentication Error' }) => { console.error(message); });
        player.addListener('account_error', ({ 'Account Error' }) => { console.error(message); });
        player.addListener('playback_error', ({ 'Playback Error' }) => { console.error(message); });

        // Playback status updates
        player.addListener('player_state_changed', state => { console.log(state); });

        // Ready
        player.addListener('ready', ({ device_id }) => {
          console.log('Ready with Device ID', device_id);
        });

        // Not Ready
        player.addListener('not_ready', ({ device_id }) => {
          console.log('Device ID has gone offline', device_id);
        });

        // Connect to the player!
        player.connect();
      };
    </script>
  </body>
</html>